spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: root
    password: marcos
    dbcp2:
      test-while-idle: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
